name: Check Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checks
        run: ./ci.sh
